name: Quality tests

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
    inputs:
      coverage_artifact_name:
        type: string
        required: true
      coverage_folder:
        type: string
        required: true
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Verify Sonar Token
        run: |
          if [ -n "$SONAR_TOKEN" ]; then
            echo "Sonar token is set and has $(echo -n $SONAR_TOKEN | wc -c) characters."
          else
            echo "SONAR_TOKEN is not set."
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Donwload coverage
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.coverage_artifact_name}}
          path: ${{inputs.coverage_folder}}

      - name: List coverage files
        run: ls -R ${{ inputs.coverage_folder }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        args: -X
