name: Quality tests

on:
  workflow_call:
    secrets:
      SONAR_CLOUD_TOKEN:
        required: true
    inputs:
      coverage_artifact_name:
        type: string
        required: true
      coverage_folder:
        type: string
        required: true
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Donwload coverage
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.coverage_artifact_name}}
          path: ${{inputs.coverage_folder}}
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
