name: CI Security

on: workflow_call

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      ENABLE_CORS: true
      PORT: 3000
      DATABASE_PORT: 5432
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_HOST: 127.0.0.1
      JWT_SECRET: c55347bb633ce8d0f4824b017f70ddb0e0336b789a5dbf7449b54af155eaf973
      JWT_REFRESH_SECRET: c08f7fd6b67152afac129cd5162959ec52576603a0d253c4b2a447dd8972f551
      ACCESS_TOKEN_EXPIRATION: 1d
      REFRESH_TOKEN_EXPIRATION: 1y

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Start the app
        run: npm run start:prod &

      - name: Wait for the app to be ready
        run: npx wait-on 127.0.0.1:3000

      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: '127.0.0.1:3000'
